#!/bin/sh
show_help() {
    echo "Usage: traffic-limiter INTERFACE RATE"
    echo "  INTERFACE: the netowrk interface to limit"
    echo "  RATE in bits per second"
}

for i in "$@"; do
    case $i in
        -h|--help|help)
        show_help
        exit 0
        ;;
    esac
done

iface=${1:-""}
rate=${2:-""}
bucket_size=""

CONFIG_HZ=$(cat /proc/config.gz | gunzip | grep CONFIG_HZ=)
HZ="${CONFIG_HZ#*=}"

rate_value="${rate}"
bucket_size=$(expr ${rate_value} / ${HZ} / 8)
if [ ${bucket_size} -eq 0 ]; then
    bucket_size=1
fi

tc qdisc del dev ${iface} root
tc qdisc add dev ${iface} root tbf rate ${rate} latency 20ms burst ${bucket_size}
