#!/bin/sh
show_help() {
    echo "Usage: traffic-limiter INTERFACE RATE"
    echo "  INTERFACE: the netowrk interface to limit"
    echo "  RATE: in mbit/s"
}

for i in "$@"; do
    case $i in
        -h|--help|help)
        show_help
        exit 0
        ;;
    esac
done

iface=${1:-""}
rate=${2:-""}
bucket_size=""

CONFIG_HZ=$(cat /proc/config.gz | gunzip | grep CONFIG_HZ=)
HZ="${CONFIG_HZ#*=}"

bucket_size=$(expr ${rate} '*' 1000000 / ${HZ} / 8 )
if [ ${bucket_size} -lt 5000 ]; then
    bucket_size=5000
fi

tc qdisc del dev ${iface} root
tc qdisc add dev ${iface} root tbf rate ${rate}mbit latency 100ms burst ${bucket_size}
